name: monitor
channels:
  - pytorch
  - defaults
dependencies:
  - aom=3.6.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.3.2
  - contourpy=1.3.1
  - cpuonly=2.0
  - cycler=0.11.0
  - dav1d=1.2.1
  - expat=2.7.1
  - filelock=3.17.0
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libcxx=20.1.8
  - libdeflate=1.22
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.4
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libtiff=4.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openjpeg=2.5.4
  - openssl=3.0.18
  - packaging=25.0
  - pcre2=10.46
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pycparser=2.23
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.3
  - requests=2.32.5
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - torchvision=0.20.1
  - typing_extensions=4.15.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - anyio==4.11.0
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - click==8.3.0
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fqdn==1.5.1
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.0.1
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.15
      - lark==1.3.1
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - open-clip-torch==3.2.0
      - opencv-python==4.12.0.88
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.5.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - python-json-logger==4.0.0
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.10.23
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - safetensors==0.6.2
      - send2trash==1.8.3
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - sympy==1.13.1
      - terminado==0.18.1
      - timm==1.0.21
      - tinycss2==1.4.0
      - tomli==2.3.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typer-slim==0.20.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.14
prefix: /opt/miniconda3/envs/monitor
